
name: Docker Image for master branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Extract ref/branch name
        shell: bash
        run: echo "##[set-output name=ref;]$(echo ${GITHUB_REF##*/})"
        id: extract_ref

      - name: Set timestamp
        shell: bash
        run: echo "::set-output name=time::$(date +%s)"
        id: set_timestamp

      - name: Login to Docker
        env:
          DOCKER_PASSWORKD: ${{ secrets.DOCKER_PASSWORKD }}
        run: docker login -u=${DOCKER_LOGIN} -p=${DOCKER_PASSWORKD}

      - name: Build Docker Image
        run:
          docker build
          --build-arg "KOWL_GIT_SHA=${GITHUB_SHA}"
          --build-arg "KOWL_GIT_REF=${{ steps.extract_ref.outputs.ref }}"
          --build-arg "KOWL_TIMESTAMP=${{ steps.set_timestamp.outputs.time }}"
          --build-arg "BUILT_FROM_PUSH=true"
          -t klinux/kowl:master-$(echo ${GITHUB_SHA} | cut -c1-8)
          -t klinux/kowl:master
          .

      - name: Push Image
        run: |
          docker push klinux/kowl:master-$(echo ${GITHUB_SHA} | cut -c1-8)
          docker push klinux/kowl:master
