
name: Docker Image on new release

on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Extract ref/branch name
        shell: bash
        run: echo "##[set-output name=ref;]$(echo ${GITHUB_REF##*/})"
        id: extract_ref

      - name: Set timestamp
        shell: bash
        run: echo "::set-output name=time::$(date +%s)"
        id: set_timestamp

      - name: Login to Docker
        env:
          DOCKER_PASSWORKD: ${{ secrets.DOCKER_PASSWORKD }}
        run: docker login -u=${DOCKER_LOGIN} -p=${DOCKER_PASSWORKD}

      - name: Build Docker Image
        run:
          docker build
          --build-arg "KOWL_GIT_SHA=${GITHUB_SHA}"
          --build-arg "KOWL_GIT_REF=${{ steps.extract_ref.outputs.ref }}"
          --build-arg "KOWL_TIMESTAMP=${{ steps.set_timestamp.outputs.time }}"
          -t klinux/kowl:${{ steps.extract_ref.outputs.ref }}
          .

      - name: Push Image
        run: |
          docker push klinux/kowl:${{ steps.extract_ref.outputs.ref }}
